version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
      
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456oz
      MYSQL_DATABASE: nodejs_sample
    ports:
      - "3306:3306"
