pipeline {
    agent any

    stages {
        stage('npm build') {
            steps {
                //Docker() 
                //bat 'docker build .'
                dir('sampleapp') {
                    bat 'npm install'
                    bat 'npm start'
                }
            }
        }
    }
}